const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#E53935",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#fafafa",
    cardForeground: "#0a0a0a",
    primary: "#E53935",
    primaryForeground: "#ffffff",
    secondary: "#f4f4f5",
    secondaryForeground: "#1a1a1a",
    muted: "#f4f4f5",
    mutedForeground: "#737373",
    accent: "#fee2e2",
    accentForeground: "#991b1b",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#fafafa",
    tint: "#FF5252",
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#171717",
    cardForeground: "#fafafa",
    primary: "#FF5252",
    primaryForeground: "#ffffff",
    secondary: "#1f1f1f",
    secondaryForeground: "#fafafa",
    muted: "#262626",
    mutedForeground: "#a3a3a3",
    accent: "#3f1d1d",
    accentForeground: "#fecaca",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#262626",
    input: "#262626",
  },
  radius: 14,
};

export default colors;
